{{- if .Values.autoscling.enabled }}
apiVersion: autoscaling/v2                              ### Описание autoscaling
kind: HorizontalPodAutoscaler

metadata:
  name: {{ .Release.Name }}-hpa                           # Название autoscaling

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment                                      # Что будет аутоскелить - Deployment
    name: {{ .Release.Name }}-deployment                  # С каким названием деплоймент будет автоскеллить (совпадает с названием деплоймента)

  minReplicas: {{ .Values.autoscling.minReplicas }}       # Минимальное количество подов 
  maxReplicas: {{ .Values.autoscling.maxReplicas }}       # Максимальное количество подов

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscling.cpuUtilization }}   # Если средняя нагрузка на поды будет выше 50%, то autoscaling добавит подов, если ниже, по убавит их количество

  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscling.memoryUtilization }} # Если средняя нагрузка на поды будет выше 80%, то autoscaling добавит подов, если ниже, по убавит их количество
{{- end }}